#!/usr/bin/env python

import sys
import shutil
from opt.parse import OptionParser

parser = OptionParser()
parser.add_option("--service_type", dest="service_type")
parser.add_option("--service_name", dest="service_name")
parser.add_option("--module_path", dest="module_path")
parser.add_option("--roll_path", dest="roll_path")
parser.add_option("--artifact_path", dest="artifact_path")
(options,args) = parser.parse_args()

fileconf = "/etc/puppet/fileserver.conf"
module_file_name = service_name + ".pp"
#artifact_path= "Staging-morservice-deploy"
#service_type = 'web'
#service_name = "morservice"
#module_path = '/etc/puppet/environments/skytap/modules/deployment_modules/manifests/'
#roll_path = '/etc/puppet/environments/skytap/manifests/roles/'





with open(fileconf, "a") as myfile:
    myfile.write("\n[" + module_file_name + "]\n" + artifact_path + "\n allow *" )

 # create file in /etc/puppet/environments/skytap/modules
outfile = open (module_path + module_file_name,'wb')

outfile.write('''class %s::%s($%s_services={})
{
  create_resources(general::%s_service, $%s_services)
}
''' % (service_name, service_name, service_name, service_type, service_name))
outfile.close()

outfile = open (roll_path + module_file_name,'wb')

outfile.write('''class roles::%s{
        tag '%s'

        include %s::%s
}
''' % (service_name, service_name, service_name, service_name))
outfile.close()
